/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgot_password` | `/forgot_password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/countries` | `/countries`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/meal` | `/meal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/meal/[id]` | `/meal/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/forgot_password` | `/forgot_password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/countries` | `/countries`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/meal` | `/meal`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/meal/[id]` | `/meal/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/forgot_password${`?${string}` | `#${string}` | ''}` | `/forgot_password${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signin${`?${string}` | `#${string}` | ''}` | `/signin${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/countries${`?${string}` | `#${string}` | ''}` | `/countries${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/meal${`?${string}` | `#${string}` | ''}` | `/meal${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgot_password` | `/forgot_password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/countries` | `/countries`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/meal` | `/meal`; params?: Router.UnknownInputParams; } | `${'/(dashboard)'}/meal/${Router.SingleRoutePart<T>}` | `/meal/${Router.SingleRoutePart<T>}` | { pathname: `${'/(dashboard)'}/meal/[id]` | `/meal/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
